[package]
name = "serde_view_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2" }
darling = "0.14"
convert_case = "0.6.0"